#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Installing requires running in sudo mode" && echo "Continuing .. you will be prompted to enter credentials for install"
fi

cmake -S . -B Build && cd Build && sudo cmake --install . 
cd ..

exit $?
